# copied and modified from travix/hystrix-dashboard

FROM travix/base-debian-jre8:latest

MAINTAINER Travix

# build time environment variables
ENV HYSTRIX_DASHBOARD_VERSION=1.5.9 \
    JETTY_RUNNER_VERSION=9.3.6.v20151106

WORKDIR /app

# install hystrix dashboard and jetty runner
RUN curl https://repo1.maven.org/maven2/com/netflix/hystrix/hystrix-dashboard/$HYSTRIX_DASHBOARD_VERSION/hystrix-dashboard-$HYSTRIX_DASHBOARD_VERSION.war -o hystrix-dashboard.war \
    && curl https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-runner/$JETTY_RUNNER_VERSION/jetty-runner-$JETTY_RUNNER_VERSION.jar -o jetty-runner.jar

EXPOSE 8080

CMD [ "java", "-cp", "jetty-runner.jar", "org.eclipse.jetty.runner.Runner", "hystrix-dashboard.war" ]